server:
  port: 8085
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
      routes:
        - id: user_service
          uri: http://localhost:9090
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1